### ISSUE TITLE
Error when attempting to login to phin api

### ISSUE THREAD

**Issue by neketu** [StarDylan/pyPhin#12]
Exception: Request not Successful! Request={"code":"InvalidVersion","success":false,"message":"1.0.0 is not supported by POST /signincontact","statusCode":400,"errors":[{"message":"1.0.0 is not supported by POST /signincontact"}]}

**Comment by StarDylan** [comment]
Yep I see the issue, they changed their API and got rid of the old version. I will work on fixing it.

**Comment by StarDylan** [comment]
It appears that the service for pHin is shutting down, as such, I will archive this repository.
